name: Deploy the main branch to Firebase

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn test

  main:
    needs: test
    name: Build and deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn add sharp --ignore-engines
      - run: NODE_OPTIONS=--openssl-legacy-provider yarn build
      - uses: lowply/deploy-firebase@v0.0.5
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: my-personal-site-6b725
